### ISSUE TITLE
Undefined offset notice on roles upgraded from Drupal 7

### ISSUE THREAD

**Issue by abetomas** [backdrop-contrib/content_access#10]
The message below appears for authenticated users accessing the 'Manage Content' screen.  
- The message does not appear if login user has all privileges allowed for the site
- It is not flagged as an error in the message log

_Notice: Undefined offset: 3 in content_access_get_gid_from_role() (line 364 of /Applications/MAMP/htdocs/rc-2c/modules/content_access/content_access.module)_
![Screen Shot 2022-07-27 at 6 27 35 PM](https://user-images.githubusercontent.com/9346415/181398322-72a2f2b9-76ad-431a-9eee-8f8ef66b72a3.png)
![Screen Shot 2022-07-27 at 6 20 06 PM](https://user-images.githubusercontent.com/9346415/181398495-f47f9fc1-8ace-434a-ab59-cdea522dfb55.png)

Thanks for any help.

**Comment by olafgrabienski** [comment]
I get nearly the same error for user accounts with several custom roles, e.g.

- Undefined offset: 4 in content_access_get_gid_from_role() (line 364 ...
- Undefined offset: 5 in content_access_get_gid_from_role() (line 364 ...

... where `4` and `5` is the Machine name of the respective role.

On my site, btw an upgrade from Drupal 7, the messages appear also in the DBlog (and there are many of them).

**Comment by laryn** [comment]
I took a quick look at the function here:

https://github.com/backdrop-contrib/content_access/blob/1.x-1.x/content_access.module#L354-L380

Perhaps all we need to do to get rid of the notices would be to check if `$gids[$rid]` exists before assigning its value in line 364: `$roles[] = $gids[$rid];`?

e.g. replace line 364 with something like this:

```
if (!empty($gids[$rid])) {
  $roles[] = $gids[$rid];
}
```

**Comment by laryn** [comment]
@abetomas Are you able to test the above?

**Comment by olafgrabienski** [comment]
```
if (!empty($gids[$rid])) {
  $roles[] = $gids[$rid];
}
```

Tested, and it works: After applying the change on my site, the messages are gone. At first sight, I didn't see any side-effects, but note that I don't know what to look at.

**Comment by abetomas** [comment]
> @abetomas Are you able to test the above?

Thanks for your response @laryn.   I recently had to deploy my site to production without the content_access module.
However, I still need the functionality of content access and reinstalled the module (v1.x-1.2.1) on my local test MAMP setup  cloned from production.  _Unfortunately, I can no longer reproduce the error messages I reported earlier with the test site I am working on._  My apologies, I would like to help in testing but I am not sure how to first replicate issue #10.  Thanks again.

**Comment by laryn** [comment]
@abetomas If you figure out how to test it would be great.

@olafgrabienski Does the functionality still work as you expect for any roles that were part of the upgrade? (Drupal 7 roles come through the upgrade process with numeric machine names and seem to be the ones that are in question here).

**Comment by olafgrabienski** [comment]
@laryn Thanks for the hint! Quickly tested: One of the upgraded roles has the *Content Access* permission "Edit own {custom-content-type} content". With the PR applied, a user with that role is still able to edit *own* content of that type (as expected) but *not other* content of that type (also as expected). So, as far as I can tell, the functionality works with the PR.

**Comment by laryn** [comment]
Thanks, this seems safe enough so I'll merge this fix and make a new release.
