### ISSUE TITLE
Rules integration: Can't set per content permissions for content type page

### ISSUE THREAD

**Issue by nattywebdev** [backdrop-contrib/content_access#19]
I'm trying to use Rules to set permissions on a node when a boolean field (field_members_only) is set to true, but am seeing an error in the debug output.

[This is on a D7 site upgraded to Backdrop]

I get the message:
Can't set per content permissions for content type page. Make sure to have per content settings activated for content types you want to alter access control for.

However, the 'per content settings' is indeed activated for the content type ('page').

The relevant Rule follows this logic:
```json
{ "rules_set_content_permission_for_members" : {
    "LABEL" : "Set content permission to members only",
    "PLUGIN" : "reaction rule",
    "OWNER" : "rules",
    "REQUIRES" : [ "rules", "content_access_rules" ],
    "ON" : { "node_insert" : [], "node_update" : [] },
    "IF" : [
      { "entity_has_field" : { "entity" : [ "node" ], "field" : "field_members_only" } },
      { "data_is" : { "data" : [ "node:field-members-only" ], "value" : "1" } }
    ],
    "DO" : [
      { "content_access_action_revoke_node_permissions" : {
          "node" : [ "node" ],
          "permissions" : { "value" : [
              "view:anonymous",
              "view:3",
              "view_own:anonymous",
              "view_own:3",
              "update:3",
              "update_own:3",
              "delete:3",
              "delete_own:3"
            ]
          }
        }
      },
      { "content_access_action_grant_node_permissions" : {
          "node" : [ "node" ],
          "permissions" : { "value" : [
              "view:authenticated",
              "view:3",
              "view_own:authenticated",
              "view_own:3",
              "update:4",
              "update:3",
              "update_own:4",
              "update_own:3",
              "delete:4",
              "delete:3",
              "delete_own:4",
              "delete_own:3"
            ]
          }
        }
      },
      { "backdrop_message" : { "message" : "Access for this content is now set to members only." } }
    ]
  }
}
```

Am I doing something wrong here? I had this working fine in D7 but can't get it to work on my Backdrop site.

Martin

**Comment by argiepiano** [comment]
Try adding an "Entity is of type" to the Conditlions.

**Comment by argiepiano** [comment]
Hmm.. I don't think will make a difference. Can you check your config folder for `content_access_NODE_TYPE.json` and check the `per_node` settings? Is it set to 1?

Also, have you "Rebuilt permissions" after enabling per-node access?

**Comment by nattywebdev** [comment]
Thanks @argiepiano for the suggestion. Tried that and it makes no difference. The Content Access is unchanged, and the same notice appears:

Debug: Can't set per content permissions for content type page. Make sure to have per content settings activated for content types you want to alter access control for.

**Comment by argiepiano** [comment]
OK, I found the bug. `_content_access_rules_check_setting()` checks the wrong config file, a file that doesn't exist. Simple thing to fix. I'll try to get a PR.

**Comment by nattywebdev** [comment]
You've done that before I even had chance to check the config! Impressive - and thank you.

For completion, there is only one config file is content_access.settings.json and this does indeed specify "per_node": 1 for each content type.

**Comment by argiepiano** [comment]
@nattywebdev, please test the provided PR #20.

**Comment by nattywebdev** [comment]
Tested and works exactly as it should. Thank you @argiepiano for an impressively swift response.

**Comment by laryn** [comment]
Thank you @argiepiano for the quick fix, and @nattywebdev for reporting and testing. Code looks good so based on the WFM above I will merge this in.

**Comment by laryn** [comment]
I'm hoping to fix #15 and #18 this week and then will make a new release.

**Comment by nattywebdev** [comment]
Was a new release issued? I just came across this issue again on a different site and remembered to check. Doesn't appear like there has been a new release, so is it coming soon (please!) @laryn ?

**Comment by laryn** [comment]
@nattywebdev Hopefully soon. I have to find time to get back to those other blockers for the next release, but I realize it's getting increasingly urgent for those as upgrades since that change may not work well with the current version.

**Comment by nattywebdev** [comment]
And I'm back again for yet another site and find this issue isn't yet fixed in the latest release (1.x-1.3.0). Any chance of getting this issue fixed in the latest release please?

**Comment by argiepiano** [comment]
Use the dev version. I don't think there is a new release yet.

**Comment by laryn** [comment]
@nattywebdev The blockers listed above have been merged. Would you be willing to test the dev version and let me know if all looks well? Then I'll make a new release.

**Comment by nattywebdev** [comment]
I certainly can do. Can you tell me where I find the dev version please?

**Comment by laryn** [comment]
@nattywebdev If you click on the "Code" button on the main repo page, it will give you a variety of ways to get the dev version: 
![CleanShot 2024-08-29 at 11 07 18@2x](https://github.com/user-attachments/assets/fa1e21d4-1179-4771-992b-3976c9573e37)

**Comment by nattywebdev** [comment]
Downloaded and copied to the modules directory. All seems well but when I click the Configure button for Content Access in the modules list I see this error:

SQLSTATE[42S02]: Base table or view not found: 1146 Table 'backdrop.content_access_node_access_rebuild' doesn't exist: SELECT canar.`nid` AS `nid`, canar.`uid` AS `uid` FROM {content_access_node_access_rebuild} canar ORDER BY timestamp ASC; Array ( )

Does that make any sense to you @laryn ?

(this is on a site upgraded from D7 a year or more ago.)

**Comment by laryn** [comment]
@nattywebdev Do you have site updates that need to be run?

**Comment by nattywebdev** [comment]
No - just checked.

The full message from the log is:
PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'backdrop.content_access_node_access_rebuild' doesn't exist: SELECT canar.`nid` AS `nid`, canar.`uid` AS `uid` FROM {content_access_node_access_rebuild} canar ORDER BY timestamp ASC; Array ( ) in content_access_get_rebuild_data() (line 836 of /app/web/modules/content_access/content_access.module).

**Comment by laryn** [comment]
@nattywebdev It sure looks like this update was not run for some reason:

https://github.com/backdrop-contrib/content_access/blob/1.x-1.x/content_access.install#L184-L202

What is the schema version for this module in the `system` table?

**Comment by nattywebdev** [comment]
schema version for content_access is 1003.

**Comment by nattywebdev** [comment]
AHA. I had checked for updates and it said none were needed. I ran cron and checked again and it then said an update was needed (content_access). I've run that and the schema version is now showing correctly as 1004.

**Comment by nattywebdev** [comment]
@laryn the error has gone away and the module is working as it should with Rules behaving as expected. I'm using a Rule to change access permission to and from anonymous on a particular node. Success! Thank you so much.

**Comment by laryn** [comment]
Excellent, thanks for testing. I've made a new release.
