### ISSUE TITLE
Commit history

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/content_access#2]
Just happened to notice that the commit history from the Drupal module didn't get included -- do we need to repull from Drupal and then commit Backdrop changes on top of it again?

**Comment by docwilmot** [comment]
Ouch. Missed that; pulled from @biolithic repo and never noticed. Yes will have to as you recommended. Can you do that? I wont have access for a while.

**Comment by laryn** [comment]
Sure, I can do it but not sure I can overwrite this repo with it. Should I just do it into a personal repo and then we can move it here once somebody deletes this version? I can prepare the Drupal version and then you can overwrite with your changes, unless you don't care about the commit being attached to you I can do that step, too.

**Comment by docwilmot** [comment]
yea sure, just do the commit over the drupal commits then force push it directly instead of doing a PR.

**Comment by laryn** [comment]
Okay, will try it.

**Comment by laryn** [comment]
@docwilmot Success, I think... and also raises the question of the `content_access_rules` submodule that was not there before. Maybe worth saving for when [Rules](https://github.com/backdrop-contrib/rules) is fully operational?

**Comment by docwilmot** [comment]
We could add that later if somebody asks for it, but I didnt check it so I dont think it is ready for release. Unless you feel to port it I'd say lets get what we've got out now so at least we have one working content access module.

**Comment by laryn** [comment]
Okay, I will remove it for now.
