### ISSUE TITLE
Allow background permission rebuild

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/content_access#21]
The latest commit in the Drupal version allows background permission rebuilding, which is a nice option.

https://www.drupal.org/project/content_access/issues/3363528

**Comment by bugfolder** [comment]
It looks like this change makes the contrib module [Node Access Rebuild Progressive](https://backdropcms.org/project/node_access_rebuild_progressive) no longer necessary (if one turns on background rebuilding in this module), yes?

**Comment by laryn** [comment]
I believe so, yes.
