### ISSUE TITLE
Error: Unsupported operand types in content_access_get_settings()

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/content_access#3]
`Error: Unsupported operand types in content_access_get_settings() (line 221 of /home/www/modules/content_access/content_access.module).`

This fatal error occurs (I believe) after adding a new content type after setting up Content Access. In my case it was erroring on webforms only. I went into the live config which didn't have an entry for webform, and adding a blank entry there seems to have solved it.

**Original config:**

```
{
    "_config_name": "content_access.settings",
    "content_access_article": [],
    "content_access_page": [],
    "gids": {
        "anonymous": 111,
        "authenticated": 222,
        "administrator": 333
    },
    "content_access_post": []
}
```

**I added** (above `content_access_post`):

```
    "content_access_webform": [],
```

**Comment by john-haus** [comment]
I'm getting the same issue, but editing the config file doesn't seem help. Moreover, this seemed working fine, but now errors when trying to access any content type access control

**Comment by john-haus** [comment]
Are the any plans to address this issue? I've been unable to get this module to work, as everytime I add a content type it effectively breaks the permissions.

**Comment by laryn** [comment]
@padprint Are you able/willing to test the `1.x-1.x` branch?
https://github.com/backdrop-contrib/content_access/tree/1.x-1.x

**Comment by john-haus** [comment]
Absolutely!  I'll test it on my site this week and let you know.

**Comment by simone960** [comment]
> @padprint Are you able/willing to test the 1.x-1.x branch?
> https://github.com/backdrop-contrib/content_access/tree/1.x-1.x

I have tested this branch and it works well ! The webform works without error and I can access to it's access control without problem. I have also tested both role based and per content node access control and it all works as designed. Thanks !

**Comment by laryn** [comment]
Thanks @simone960 -- I'm going to make an initial release. 

@padprint if you run into any issues, raise a new issue.
