### ISSUE TITLE
PHP notices when installing content_access

### ISSUE THREAD

**Issue by indigoxela** [backdrop-contrib/content_access#8]
When installing content access I get:

```
    Notice: Undefined index: hidden in installer_browser_installation_enable_form() (Zeile 653 von .../core/modules/installer/installer.pages.inc).
    Notice: Undefined index: type in installer_browser_installation_enable_form() (Zeile 655 von .../core/modules/installer/installer.pages.inc).
```
This is caused by:

content_access_rules/content_access_rules.info, which misses the required `type = module` info

Looks like a simple one-liner fix. :wink: 

For further details see also:

- https://api.backdropcms.org/modules
- https://github.com/backdrop/backdrop-issues/issues/4640

**Comment by laryn** [comment]
Good catch @indigoxela -- I must admit I haven't used that submodule yet since I took this project over... Thanks.
